# Generated by Django 3.2.6 on 2023-02-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminhod',
            name='address',
            field=models.CharField(blank=True, default='Nairobi, Kenya', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='adminhod',
            name='mobile',
            field=models.CharField(blank=True, default='07xxxxxxxx', max_length=10, null=True),
        ),
    ]
