# Generated by Django 3.2.6 on 2023-02-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_auto_20230205_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientfeedback',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='patientfeedback',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='patientfeedback',
            name='pharmacist_id',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='pharmacyclerk',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='dispense',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='dispense',
            name='taken',
        ),
        migrations.AddField(
            model_name='dispense',
            name='customer_name',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'AdminHOD'), (2, 'Front Desk')], default=1, max_length=10),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='PatientFeedback',
        ),
        migrations.DeleteModel(
            name='Patients',
        ),
        migrations.DeleteModel(
            name='Pharmacist',
        ),
        migrations.DeleteModel(
            name='PharmacyClerk',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
