# Generated by Django 3.2.6 on 2023-02-10 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_auto_20230210_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusomer_name', models.CharField(default='anonymous', max_length=55)),
                ('qty', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.DeleteModel(
            name='Dispense',
        ),
        migrations.AddField(
            model_name='drugsales',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold', to='pharmacy.stock'),
        ),
    ]
