# Generated by Django 3.2.6 on 2023-02-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_auto_20230210_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='stock',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
