# Generated by Django 3.2.6 on 2023-02-11 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_auto_20230210_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugitemssales',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='customer_id',
            field=models.CharField(blank=True, default='********', max_length=15),
        ),
        migrations.AddField(
            model_name='sales',
            name='tax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sales',
            name='tax_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='drugitemssales',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='drugitemssales',
            name='qty',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='stock',
            name='buying_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='selling_price',
            field=models.FloatField(default=0),
        ),
    ]
