# Generated by Django 3.2.6 on 2023-02-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_auto_20230211_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugitemssales',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
