# Generated by Django 3.2.6 on 2023-02-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_auto_20230211_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugitemssales',
            options={'verbose_name': 'Drug Sale Items', 'verbose_name_plural': 'Drug Sale Items'},
        ),
    ]
