# Generated by Django 3.2.6 on 2023-02-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailReceivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Email Receivers',
                'verbose_name_plural': 'Email Receivers',
            },
        ),
        migrations.AlterModelOptions(
            name='adminhod',
            options={'verbose_name': 'Pharmacist', 'verbose_name_plural': 'Pharmacists'},
        ),
    ]
