# Generated by Django 3.2.6 on 2023-02-11 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacy', '0010_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('resolved', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_notify', to='pharmacy.stock')),
            ],
            options={
                'verbose_name': 'Low Stock Notifications',
                'verbose_name_plural': 'Low Stock Notifications',
            },
        ),
    ]
